### ISSUE TITLE
[Q] Example code

### ISSUE THREAD

**Issue by hiroyuki-sato** [test-unit/test-unit-rr#4]
Hello

Is this example correct?
Do I need nested `assert_rr`?

https://github.com/test-unit/test-unit-rr/blob/master/lib/test/unit/rr.rb#L72-L78

```ruby
assert_rr do
  subject = Object.new
  assert_rr do
    mock(subject).should_be_called
    subject.should_be_called
  end
end
```

Is this wrong usage?

```ruby
subject = Object.new
assert_rr do
  mock(subject).should_be_called
  subject.should_be_called
end
```

Thanks.

**Comment by kou** [comment]
The example is wrong.
We don't need outer `assert_rr`.

**Comment by hiroyuki-sato** [comment]
Thank you for the comment.
I created #5 for fixing this issue.
